export const users = [
	{
	  id: 1,
	  name: "Veni",
	  age: 20,
	  email: "lalala@gmail.com",
	  country: "Japan",
	  company: "Intel",
	  birthday: "1/2/2023",
	},
	{
	  id: 2,
	  name: "Vidi",
	  age: 21,
	  email: "tili-tili@gmail.com",
	  country: "China",
	  company: "AMD",
	  birthday: "3/4/2023",
	},
	{
	  id: 3,
	  name: "Vici",
	  age: 23,
	  email: "trali-vali@gmail.com",
	  country: "USA",
	  company: "Amazon",
	  birthday: "5/6/2023",
	},
	{
	  id: 4,
	  name: "Dictum",
	  age: 24,
	  email: "mail@gmail.com",
	  country: "Ireland",
	  company: "Google",
	  birthday: "7/8/2023",
	},
	{
	  id: 5,
	  name: "Factum",
	  age: 25,
	  email: "bird@gmail.com",
	  country: "China",
	  company: "AliBaba",
	  birthday: "9/10/2023",
	},
 ];